### ISSUE TITLE
Flattener doesn't parse "pragma experimental"

### ISSUE THREAD

**Issue by kriskelly** [nomiclabs/truffle-flattener#22]
I have the following at the top of my contract:

```
pragma solidity ^0.4.19;
pragma experimental ABIEncoderV2;
```

`truffle-flattener contracts/Whatever.sol` fails with the following error:

```
Error: Could not parse contracts/Whatever.sol for extracting its imports.\n    at getDependencies (/Users/kriskelly/.config/yarn/global/node_modules/truffle-flattener/index.js:51
```

Digging further, it looks like the solidity parser throws this error:
```
SyntaxError: Expected "solidity", comment, end of line, or whitespace but "e" found. Line: 2, Column: 8
```

The code compiles and migrates fine with truffle. The flattener also works fine with my contracts that do not use pragma experimental.

I'm assuming that the solidity parser is out of date, not really sure how to proceed.

**Comment by alcuadrado** [comment]
Hi @kriskelly, thanks for reporting this. 

You are right, the solidity parser is outdated. I'll replace it for a more actively-developed one during the weekend.

**Comment by k06a** [comment]
Also waiting for the solution, right now commenting this line out and inserting it after flattening.

**Comment by alcuadrado** [comment]
#30 will fix this

**Comment by alcuadrado** [comment]
Closing because #30 fixed this
