### ISSUE TITLE
 Could not find XXXXXXX.sol (BasicToken.sol) from any sources

### ISSUE THREAD

**Issue by liuhuanhui** [nomiclabs/truffle-flattener#24]
Hello, I want to pack into a file for Verify Contract Code to use truffle-flattener, the following code all the following are said to be unable to find: Could not find BasicToken.sol from any sources

```
1.truffle-flattener./contracts/LhhToken.sol --output result.sol
2.truffle-flattener  $(pwd)/contracts/LhhToken.sol  --solc-paths=openzeppelin-solidity=$(pwd)/solidity/node_modules/openzeppelin-solidity/

```
![token](https://user-images.githubusercontent.com/10370625/40263838-e37879c2-5b4a-11e8-85a4-84e3185f5d9d.png)

**Comment by liuhuanhui** [comment]
Someone knows how to solve it, thank you.

**Comment by jossef** [comment]
check out this repo, I managed to successfully build a contract using `truffle-flattener`
https://github.com/bmby-co/contract

**Comment by alcuadrado** [comment]
Thanks for providing that example @jossef. I'm closing this for now. @liuhuanhui feel free to create a new issue if you still have this problem.
