### ISSUE TITLE
Flattener doesn't correctly handle import alias.

### ISSUE THREAD

**Issue by Freydal** [nomiclabs/truffle-flattener#31]
When an import is destructured and aliased the alias name is not defined.  The following example includes DetailedERC20, but Token would not be defined. 
`import {DetailedERC20 as Token} from "openzeppelin-solidity/contracts/token/ERC20/DetailedERC20.sol";
`

 I have worked around this while adding code to etherscan by manually adding:
`contract Token is DetailedERC20 {}`

**Comment by alcuadrado** [comment]
Hi @Freydal , thanks for reporting this. Unfortunately, supporting this would make this tool way more complex, as there's no way to define type aliases in Solidity. I'm not confident that your workaround would work in the general case.

I'll document this in the readme.
