### ISSUE TITLE
Normalizing version pragmas is unnecessary

### ISSUE THREAD

**Issue by frangio** [nomiclabs/truffle-flattener#37]
`truffle-flattener` currently replaces all individual version pragmas with a single "normalized" pragma at the top of the result. This normalization doesn't support version specifiers other than `^`, such as `>=` which is being used a bit lately in the ecosystem.

This isn't necessary though. The compiler supports files with multiple version pragmas throughout, so `truffle-flattener` could just leave them where they are.

**Comment by alcuadrado** [comment]
This has been fixed in version 1.3.0. Thanks for reporting it and suggesting the fix :)
