### ISSUE TITLE
Does this take into account compiler settings?

### ISSUE THREAD

**Issue by PaulRBerg** [nomiclabs/truffle-flattener#45]
For instance, the solidity optimizer and the default 200 runs. I think it would be worth it to add a note about how truffle-flattener handles the config file.

**Comment by alcuadrado** [comment]
This projects just concatenates solidity source files in the right order. It never executes `solc`, so it doesn't handle settings at all.

**Comment by PaulRBerg** [comment]
Not sure what I was thinking about. It's really late where I am.

Thank you!
