### ISSUE TITLE
Add support for Solidity 0.6 new syntax, such as "receive"

### ISSUE THREAD

**Issue by jerryji** [nomiclabs/truffle-flattener#47]
MyContract has been compiled, deployed, and tested successfully on both Ganache as well as on Rinkeby. However, truffle-flattener fails to parse it --

```
$ truffle-flattener MyContract.sol
Error: Could not parse MyContract.sol for extracting its imports: ParserError: mismatched input '(' expecting {'from', 'calldata', 'constant', 'internal', 'private', 'public', Identifier} (79:11)
    at getDependencies (/usr/lib/node_modules/truffle-flattener/index.js:44:11)
    at dependenciesDfs (/usr/lib/node_modules/truffle-flattener/index.js:64:24)
    at async getSortedFilePaths (/usr/lib/node_modules/truffle-flattener/index.js:83:5)
    at async flatten (/usr/lib/node_modules/truffle-flattener/index.js:170:23)
    at async main (/usr/lib/node_modules/truffle-flattener/index.js:227:3)

$ cat -n MyContract.sol
   1     pragma solidity ^0.6.1;
 ...
 79     receive() external payable { // solidity 0.6
 80         emit FallbackDeposit(msg.sender, uint40(now), msg.value);
 81     }
```

Please add Solidity 0.6 support, many thanks in advance.

**Comment by KaiRo-at** [comment]
Also got this (which is probably a parser issue):
Error: Could not parse /.../node_modules/@openzeppelin/contracts/token/ERC721/IERC721.sol for extracting its imports: ParserError: extraneous input 'abstract' expecting {<EOF>, 'pragma', 'import', 'contract', 'interface', 'library'} (8:0)

**Comment by KaiRo-at** [comment]
Maybe should use the `solidity-parser-diligence` fork as a parser, which may have new features, see https://github.com/consensys/solidity-parser-antlr

**Comment by jerryji** [comment]
What concerns me is solidity-parser-antlr 's latest release is on Aug 30, 2019? As Solidity 0.6.0 was released later on Dec 18, 2019, I guess some work is still needed for solidity-parser-antlr to support the Solidity 0.6 syntax.

**Comment by KaiRo-at** [comment]
> What concerns me is solidity-parser-antlr 's latest release is on Aug 30, 2019. As Solidity 0.6.0 was released later on Dec 18, 2019, I guess some work is still needed for solidity-parser-antlr to support the Solidity 0.6 syntax.

That's exactly why I pointed to `solidity-parser-diligence`, they have released this February the last time: https://www.npmjs.com/package/solidity-parser-diligence (there are still a few Solidity 0.6 issues open with it, but it mostly works - see also https://github.com/sc-forks/solidity-coverage/issues/481 for a list of `solidity-parser-diligence` issues that `solidity-coverage` is tracking for full 0.6 support)

**Comment by alcuadrado** [comment]
I just released a new version that should fix this. Please open a new issue if this problem is still present.
