### ISSUE TITLE
Solidity 0.7.0 constructor without modifier breaks parser

### ISSUE THREAD

**Issue by kongliangzhong** [nomiclabs/truffle-flattener#58]
Error: Constructors have to be declared either "public" or "internal"

**Comment by hshar7** [comment]
Also ran into this. Any news here?

**Comment by vittominacori** [comment]
Me too. Are you planning to work on this?

**Comment by alcuadrado** [comment]
We are pretty busy right now, do you mind sending a PR @vittominacori ? I think all you need to do is upgrading the parser.
