### ISSUE TITLE
Support for HardHat

### ISSUE THREAD

**Issue by naszam** [nomiclabs/truffle-flattener#71]
Hi, 

I'd like to know if you have any plans to add support for HardHat.
Would be a nice way to flatten contracts to [verify on blockscout](https://docs.blockscout.com/for-users/smart-contract-interaction/verifying-a-smart-contract) when deploying to sokol or xdai.

Just found related issue #65 and pr #66

What is the status on that? 

Thanks!

**Comment by naszam** [comment]
just found the `flatten` task for hardhat :+1:

**Comment by yurenji** [comment]
> just found the `flatten` task for hardhat 👍 The only issue with that is the Multiple SPDX license identifiers error.

could you plz point me to the `flatten` task, thanks.

**Comment by alcuadrado** [comment]
`npx hardhat flatten`
